### ISSUE TITLE
socket.gaierror: [Errno 8] 

### ISSUE THREAD

**Issue by nmt28** [icesat2py/icepyx#162]
I recently updated my version of icepyx (I was using a really old version) and also helped a colleague install icepyx. When trying to download data we both got the error:

"socket.gaierror: [Errno 8] nodename nor servname provided, or not known"

I tacked this down to socket not being able to get the localhostname adequately. I ended up changing lines 48 and 49 in Earthdata.py:

hostname = socket.gethostname("")
ip = socket.gethostbyname(hostname)

to:

"ip = "192.XXX.XX.XXX" and manually entered my IP address. 

Im running macOS Catalina but am also on a NASA machine (not sure if that would allow icepyx to fetch the IP address or not). 

Just wanted to let you know this is occurring and this is a solution for anyone else that comes across this.

Otherwise icepyx is AWESOME!

**Comment by JessicaS11** [comment]
Thanks for getting in touch, @nmt28, and sharing your issue and solution. It sounded familiar to me, and after some digging it turns out others had had this issue before (#97). It was fixed (#98), and then I managed to promptly partially undo the advances when later merging in an earlier (#96) PR. I'll get the fix back into the development branch so that it will be in the next release.

Thanks as well for the kudos! Please join one of our [upcoming meetings](https://discourse.pangeo.io/t/icepyx-team-meetings/722/5?u=jessicas11) to let us know how you're using icepyx and where you'd like to see it go in the future.

**Comment by nmt28** [comment]
Thanks @JessicaS11. I did look out for a past issue but only browsed the 'open' issues' - D'oh! But at least we caught the bug (again!).

Will definitely keep an eye out for upcoming meetings!

**Comment by JessicaS11** [comment]
That's reasonable (only looking at open issues!). Thanks for catching it (again!).
