### ISSUE TITLE
Geoviews as a dependency given install challenges

### ISSUE THREAD

**Issue by JessicaS11** [icesat2py/icepyx#177]
>> Paying attention to the geoviews install challenges is especially important (many users are still new to creating and updating environments, so this presents an extra hurdle for them). It's also the cause of the Travis CI failure - it needs PROJ to install cartopy, which is a geoviews dependency. I'll try to look into how other packages handle this challenge unless you already have a proposed solution.

>Installing `PROJ` into Travis CI will be a bit involved. Either we install it using `conda` (see https://docs.conda.io/projects/conda/en/4.6.1/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file), or via something like `apt` (https://docs.travis-ci.com/user/languages/python/#dependency-management). This PR looks good, but we might have to wait to handle this after release v0.3.3 (#170), and it might be best to add `geoviews` as a dependency in a separate Pull Request to keep things manageable.

>Locally, I've been using `conda create --name icepyx --file requirements.txt` (to create a fresh `icepyx` conda environment) to test, rather than `pip install requirements.txt`. Will need to figure out how to translate that to work on `.travis.yml` (read: may need to setup miniconda first).

_Originally posted by @weiji14 in https://github.com/icesat2py/icepyx/pull/176#discussion_r589778204_

Travis CI's role is to run the testing suite prior to merges. Since geoviews (and other potentially fussy-to-install geospatial packages) are not core requirements for software functionality/testing, perhaps the best approach is to add an environment.yml file that includes geoviews, but not include it as a software requirement (since there is another option for visualization).

**Comment by weiji14** [comment]
> Since geoviews (and other potentially fussy-to-install geospatial packages) are not core requirements for software functionality/testing, perhaps the best approach is to add an environment.yml file that includes geoviews, but not include it as a software requirement (since there is another option for visualization).

Agree with having an `environment.yml` file, since [`conda`](https://docs.conda.io/en/latest/) is a common way to install both Python and non-Python dependencies nowadays.

One thing I'll add is that we can list down 'optional dependencies' in the `setup.py` file by adding an 'extra_requires' parameter. For example, [dask uses](https://github.com/dask/dask/blob/fb544144611b25a6f23d90637038a93f93153f8f/setup.py#L10-L29) the following (see also https://docs.dask.org/en/stable/install.html#pip):

```python
extras_require = {
    "array": ["numpy >= 1.15.1", "toolz >= 0.8.2"],
    "bag": [
        "cloudpickle >= 0.2.2",
        "fsspec >= 0.6.0",
        "toolz >= 0.8.2",
        "partd >= 0.3.10",
    ],
    "dataframe": [
        "numpy >= 1.15.1",
        "pandas >= 0.25.0",
        "toolz >= 0.8.2",
        "partd >= 0.3.10",
        "fsspec >= 0.6.0",
    ],
    "distributed": ["distributed >= 2021.03.0"],
    "diagnostics": ["bokeh >= 1.0.0, != 2.0.0"],
    "delayed": ["cloudpickle >= 0.2.2", "toolz >= 0.8.2"],
}
extras_require["complete"] = sorted({v for req in extras_require.values() for v in req})
```

For IcePyx, this would involve adding an 'extra_requires' line somewhere around here:

https://github.com/icesat2py/icepyx/blob/9f94a70030b92ab4db84088082460694f32008bf/setup.py#L21

Users would then be able to do something like `pip install icepyx[complete]` (after having handled the PROJ dependency themselves somehow).
