### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Sharanb02** [icesat2py/icepyx#214]
`(base)>>conda install icepyx`

`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.`

After this it just says the package is not available. I think it might be issues with dependencies but I don't know what to update for making this work.

**Comment by weiji14** [comment]
Hmm, that's weird. Did you try installing icepyx into a separate conda virtual environment using `conda create --name icepyx-env --channel conda-forge icepyx` as recommended in https://icepyx.readthedocs.io/en/latest/getting_started/install.html? If that still doesn't work, add a `-vv` to the command and post the full verbose output so we can inspect if there's an issue due to a dependency conflict.

**Comment by Sharanb02** [comment]
@weiji14  yep, I tried the git clone method of installation, that worked. but now I'm having a new problem.  I get the following error when I import the module.

FileNotFoundError: Could not find module 'C:\Users\shara\anaconda3\lib\site-packages\scipy\.libs\libbanded5x.X7D476RWJKO3TRH4FXIEB4YEAKNOYBT4.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by Sharanb02** [comment]
it worked! 

> @weiji14 yep, I tried the git clone method of installation, that worked. but now I'm having a new problem. I get the following error when I import the module.
> 
> FileNotFoundError: Could not find module 'C:\Users\shara\anaconda3\lib\site-packages\scipy.libs\libbanded5x.X7D476RWJKO3TRH4FXIEB4YEAKNOYBT4.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

it worked! I ran the `conda update scipy` command and it worked now
