### ISSUE TITLE
Can't open DAAC_DataAccess_Example notebook

### ISSUE THREAD

**Issue by simonrp84** [icesat2py/icepyx#242]
Hello,
I've just discovered icepyx and it looks like a really useful collection of tools! Am trying to familiarise myself with it, but have come across an error. when I try to open the `icepyx\examples\ICESat-2_DAAC_DataAccess_Example.ipynb` file I get:
`AttributeError('metadata')`.
Have re-downloaded the git repo several times and the error persists, I also can't load the notebook directly through github, so presumably the file is corrupted on the repo.

**Comment by JessicaS11** [comment]
Hello @simonrp84! Thanks for sharing this issue. Can you provide a few more details on how you're trying to open the notebook? I often get this error myself (it has to do with the saving of the Jupyter Notebook across versions and platforms), but I just checked and am not having the issue with the `ICESat-2_DAAC_DataAccess_Example.ipynb` file in the current development or main branches.

>I also can't load the notebook directly through github

Notebooks often are not rendered properly on GitHub... it's a known issue due to the way GitHub tries to render the notebooks. We're actually working on having our notebooks automatically rendered as part of our documentation (#196) so that users can see them without relying on GitHub.

**Comment by simonrp84** [comment]
Thanks for the reply @JessicaS11, my workflow is as follows - tested on both windows and linux machines, using recent versions of all libraries from `conda-forge`:
```
git clone git@github.com:icesat2py/icepyx.git
jupyter notebook
```
Then, once jupyter starts, I navigate to `icepyx/examples` and double click the `ICESat-2_DAAC_DataAccess_Example.ipynb` notebook. A new browser tab opens, but rather than displaying the notebook I instead get the error message listed above.

However, your comment did remind me to check the branches: This happens on the `development` branch (which is the default after cloning) but if I check out the master branch then I can load the notebook OK, so the corruption seems to be on the one branch only.
Hope that helps clarify things a bit!

**Comment by JessicaS11** [comment]
Thanks for all this info, @simonrp84!

Apparently, #213 re-introduced a bad cell (with incomplete import statements; it shows up around lines 36-37) that I can't seem to keep out of the code no matter how many times I remove it. I've updated the development branch so that it should work again... for whatever reason Jupyter Notebook gives this error, but opening the notebook in VS or as a text file does not. Please let me know if this fixes the issue!

**Comment by simonrp84** [comment]
Great! I just gave it a quick test @JessicaS11 and the notebook loads in both branches now. Thanks for the quick fix! I'll close this issue.
