### ISSUE TITLE
Unable to download  5000005497555

### ISSUE THREAD

**Issue by huangjingyuan7** [icesat2py/icepyx#523]
![1714031448591](https://github.com/icesat2py/icepyx/assets/113357157/d15bc672-0efd-47fc-9dab-fa2fb57c837f)

**Comment by JessicaS11** [comment]
Hello @huangjingyuan7! Thanks for reaching out.

It appears that your data request did not have any data for the requested location and time period. The logic for this conclusion is that your query identified two potential granules ("Total number of data order requests is 1 for 2 granules"), and then NSIDC returned a message indicating two granules (277733726 and 277724555) did not have data within the requested region. Thus, your order (with the ID 5000005497555) did not contain any granules and could not be downloaded.

For some products, this happens because the metadata used for filtering does not exactly match the spatial extent of the data within the file. If you provide some more details about your objectives, I'm happy to help you access the data you need.

Below is a graphic from the NSIDC programmatic access guide that I find helpful for visualizing the differences between subsetting and filtering.
https://nsidc.org/sites/default/files/images/filtering%2520versus%2520subsetting_2.jpg
