### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by bradlipovsky** [icesat2py/icepyx#65]
The link "ICESat-2_DAAC_DataAccess_Example" in README.rst (points to https://github.com/icesat2py/icepyx/blob/master/ICESat-2_DAAC_DataAccess_Example.ipynb) is broken.

**Comment by JessicaS11** [comment]
Thanks for pointing this out, @bradlipovsky. This is the result of the issue raised in #50; because Read The Docs and GitHub render links differently, they can only work from one place or the other. After consulting with the Pangeo team, we decided it was better to have the working ones on the doc pages over GitHub. If you're familiar with (or want to learn!) sphinx/ReadTheDocs/restructured text to try and help fix this, please let us know!
